"""Add roles column to user table

Revision ID: 505718c75d77
Revises: 
Create Date: 2024-08-31 13:51:40.503344

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '505718c75d77'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_roles')
    with op.batch_alter_table('role', schema=None) as batch_op:
        batch_op.drop_index('name')
        batch_op.drop_index('roleId')

    op.drop_table('role')
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('roles', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('is_active', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('is_active')
        batch_op.drop_column('roles')

    op.create_table('role',
    sa.Column('roleId', mysql.CHAR(length=36), nullable=False),
    sa.Column('name', mysql.VARCHAR(length=50), nullable=False),
    sa.PrimaryKeyConstraint('roleId'),
    mysql_collate='utf8mb4_general_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    with op.batch_alter_table('role', schema=None) as batch_op:
        batch_op.create_index('roleId', ['roleId'], unique=True)
        batch_op.create_index('name', ['name'], unique=True)

    op.create_table('user_roles',
    sa.Column('user_id', mysql.CHAR(length=36), nullable=False),
    sa.Column('role_id', mysql.CHAR(length=36), nullable=False),
    sa.ForeignKeyConstraint(['role_id'], ['role.roleId'], name='user_roles_ibfk_2'),
    sa.ForeignKeyConstraint(['user_id'], ['user.userId'], name='user_roles_ibfk_1'),
    sa.PrimaryKeyConstraint('user_id', 'role_id'),
    mysql_collate='utf8mb4_general_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    # ### end Alembic commands ###
